version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.7.0"
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - elk
  rest:
    build:
      context: .
      dockerfile: python-flask-server-generated/Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - "8000:8080"
    links:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
