# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.validation_error_detail import ValidationErrorDetail  # noqa: F401,E501
from swagger_server import util


class ValidationError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, detail: List[ValidationErrorDetail]=None):  # noqa: E501
        """ValidationError - a model defined in Swagger

        :param detail: The detail of this ValidationError.  # noqa: E501
        :type detail: List[ValidationErrorDetail]
        """
        self.swagger_types = {
            'detail': List[ValidationErrorDetail]
        }

        self.attribute_map = {
            'detail': 'detail'
        }
        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationError of this ValidationError.  # noqa: E501
        :rtype: ValidationError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self) -> List[ValidationErrorDetail]:
        """Gets the detail of this ValidationError.


        :return: The detail of this ValidationError.
        :rtype: List[ValidationErrorDetail]
        """
        return self._detail

    @detail.setter
    def detail(self, detail: List[ValidationErrorDetail]):
        """Sets the detail of this ValidationError.


        :param detail: The detail of this ValidationError.
        :type detail: List[ValidationErrorDetail]
        """

        self._detail = detail
