# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ValidationErrorDetail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, loc: List[str]=None, msg: str=None, type: str=None):  # noqa: E501
        """ValidationErrorDetail - a model defined in Swagger

        :param loc: The loc of this ValidationErrorDetail.  # noqa: E501
        :type loc: List[str]
        :param msg: The msg of this ValidationErrorDetail.  # noqa: E501
        :type msg: str
        :param type: The type of this ValidationErrorDetail.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'loc': List[str],
            'msg': str,
            'type': str
        }

        self.attribute_map = {
            'loc': 'loc',
            'msg': 'msg',
            'type': 'type'
        }
        self._loc = loc
        self._msg = msg
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationErrorDetail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationError_detail of this ValidationErrorDetail.  # noqa: E501
        :rtype: ValidationErrorDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loc(self) -> List[str]:
        """Gets the loc of this ValidationErrorDetail.


        :return: The loc of this ValidationErrorDetail.
        :rtype: List[str]
        """
        return self._loc

    @loc.setter
    def loc(self, loc: List[str]):
        """Sets the loc of this ValidationErrorDetail.


        :param loc: The loc of this ValidationErrorDetail.
        :type loc: List[str]
        """

        self._loc = loc

    @property
    def msg(self) -> str:
        """Gets the msg of this ValidationErrorDetail.


        :return: The msg of this ValidationErrorDetail.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this ValidationErrorDetail.


        :param msg: The msg of this ValidationErrorDetail.
        :type msg: str
        """

        self._msg = msg

    @property
    def type(self) -> str:
        """Gets the type of this ValidationErrorDetail.


        :return: The type of this ValidationErrorDetail.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ValidationErrorDetail.


        :param type: The type of this ValidationErrorDetail.
        :type type: str
        """

        self._type = type
