# coding: utf-8

"""
    Spec

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.movies_api import MoviesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMoviesApi(unittest.TestCase):
    """MoviesApi unit test stubs"""

    def setUp(self):
        self.api = MoviesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_movie_by_id(self):
        """Test case for get_movie_by_id

        Получить фильм  # noqa: E501
        """
        pass

    def test_list_movies(self):
        """Test case for list_movies

        Список фильмов  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
