# coding: utf-8

"""
    Spec

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.short_movie import ShortMovie  # noqa: E501
from swagger_client.rest import ApiException


class TestShortMovie(unittest.TestCase):
    """ShortMovie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShortMovie(self):
        """Test ShortMovie"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.short_movie.ShortMovie()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
